language: java
jdk:
  - openjdk6
  - oraclejdk7
notifications:
    email: false
    irc: "irc.wma.im#minecraft-dev"
install: "mvn clean install"
script: "mvn package"
branches:
  only:
    - development
